CREATE TABLE US_Congress (
    bioguide_id text CONSTRAINT p_key_uscongress PRIMARY KEY,
    date_added date DEFAULT CURRENT_DATE NOT NULL,
    last_updated timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_name text NOT NULL,
    first_name text NOT NULL,
    middle_name text,
    suffix text,
    nickname text,
    full_name text NOT NULL,
    birthday date NOT NULL,
    gender text,
    type text NOT NULL,
    state text NOT NULL,
    district integer,
    senate_class integer,
    party text NOT NULL,
    url text,
    address text,
    phone text,
    fax_number text,
    fax_zero_url text,
    contact_form text,
    rss_url text UNIQUE,
    twitter text UNIQUE,
    twitter_id bigint UNIQUE,
    facebook text UNIQUE,
    youtube text UNIQUE,
    youtube_id text UNIQUE,
    mastodon text UNIQUE,
    thomas_id integer UNIQUE,
    opensecrets_id text UNIQUE,
    lis_id text UNIQUE,
    fec_ids text UNIQUE,
    cspan_id integer UNIQUE,
    govtrack_id integer UNIQUE,
    votesmart_id integer UNIQUE,
    ballotpedia_id text UNIQUE,
    washington_post_id text UNIQUE,
    icpsr_id integer UNIQUE,
    wikipedia_id text UNIQUE
    );
