SELECT us_congress.last_name,us_congress.first_name,us_congress.nickname,us_congress.middle_name,us_congress.suffix,us_congress.full_name,
	us_congress.bioguide_id,us_congress.google_api_name,(
	SELECT raw.name
	FROM (
		VALUES
		('AK','Dan Sullivan','S001198'),
		('AK','Lisa Murkowski','M001153'),
		('AK','Mary Sattler Peltola','Not Found'),
		('AL','Katie Boyd Britt','Not Found'),
		('AL','Tommy Tuberville','Not Found'),
		('AL','Terri Sewell','Not Found'),
		('AL','Gary Palmer','Not Found'),
		('AL','Jerry Carl','Not Found'),
		('AL','Mike Rogers','R000575'),
		('AL','Barry Moore','Not Found'),
		('AL','Dale Strong','Not Found'),
		('AL','Robert B. Aderholt','Not Found'),
		('AR','John Boozman','B001236'),
		('AR','Tom Cotton','C001095'),
		('AR','Bruce Westerman','Not Found'),
		('AR','Steve Womack','W000809'),
		('AR','French Hill','Not Found'),
		('AR','Rick Crawford','C001087'),
		('AS','Amata Radewagen','Not Found'),
		('AZ','Kyrsten Sinema','Not Found'),
		('AZ','Mark Kelly','Not Found'),
		('AZ','Paul Gosar','Not Found'),
		('AZ','Debbie Lesko','Not Found'),
		('AZ','Andy Biggs','Not Found'),
		('AZ','Greg Stanton','Not Found'),
		('AZ','Raúl Grijalva','Not Found'),
		('AZ','Juan Ciscomani','Not Found'),
		('AZ','David Schweikert','Not Found'),
		('AZ','Ruben Gallego','Not Found'),
		('AZ','Eli Crane','Not Found'),
		('CA','Alex Padilla','Not Found'),
		('CA','Dianne Feinstein','F000062'),
		('CA','Jared Huffman','H001068'),
		('CA','Doug LaMalfa','L000578'),
		('CA','Mike Thompson','Not Found'),
		('CA','Kevin Kiley','Not Found'),
		('CA','Ami Bera','Not Found'),
		('CA','Tom McClintock','Not Found'),
		('CA','John Garamendi','Not Found'),
		('CA','Doris Matsui','Not Found'),
		('CA','Josh Harder','Not Found'),
		('CA','Nancy Pelosi','Not Found'),
		('CA','Mark DeSaulnier','Not Found'),
		('CA','John Duarte','Not Found'),
		('CA','Barbara Lee','Not Found'),
		('CA','Kevin Mullin','Not Found'),
		('CA','Eric Swalwell','Not Found'),
		('CA','Ro Khanna','Not Found'),
		('CA','Anna G. Eshoo','Not Found'),
		('CA','Jimmy Panetta','Not Found'),
		('CA','Zoe Lofgren','Not Found'),
		('CA','David G. Valadao','Not Found'),
		('CA','Jim Costa','Not Found'),
		('CA','Salud O. Carbajal','Not Found'),
		('CA','Jay Obernolte','Not Found'),
		('CA','Julia Brownley','B001285'),
		('CA','Raul Ruiz','Not Found'),
		('CA','Judy Chu','Not Found'),
		('CA','Mike Garcia','Not Found'),
		('CA','Kevin McCarthy','Not Found'),
		('CA','Sara Jacobs','Not Found'),
		('CA','Scott Peters','Not Found'),
		('CA','Juan Vargas','Not Found'),
		('CA','Tony CÃ¡rdenas','Not Found'),
		('CA','Pete Aguilar','Not Found'),
		('CA','Brad Sherman','Not Found'),
		('CA','Norma J. Torres','Not Found'),
		('CA','Jimmy Gomez','Not Found'),
		('CA','Sydney Kamlager-Dove','Not Found'),
		('CA','Ted W. Lieu','Not Found'),
		('CA','Mark Takano','Not Found'),
		('CA','Linda T. Sánchez','S001156'),
		('CA','Grace F. Napolitano','Not Found'),
		('CA','Adam Schiff','Not Found'),
		('CA','Nanette Diaz BarragÃ¡n','Not Found'),
		('CA','Maxine Waters','W000187'),
		('CA','Lou Correa','Not Found'),
		('CA','Michelle Steel','Not Found'),
		('CA','Darrell Issa','Not Found'),
		('CA','Katie Porter','Not Found'),
		('CA','Mike Levin','Not Found'),
		('CA','Young Kim','Not Found'),
		('CA','Robert Garcia','Not Found'),
		('CA','Ken Calvert','Not Found'),
		('CO','John W. Hickenlooper','Not Found'),
		('CO','Michael F. Bennet','B001267'),
		('CO','Brittany Pettersen','Not Found'),
		('CO','Yadira Caraveo','Not Found'),
		('CO','Lauren Boebert','Not Found'),
		('CO','Ken Buck','Not Found'),
		('CO','Doug Lamborn','Not Found'),
		('CO','Jason Crow','Not Found'),
		('CO','Diana DeGette','Not Found'),
		('CO','Joe Neguse','Not Found'),
		('CT','Christopher Murphy','Not Found'),
		('CT','Richard Blumenthal','B001277'),
		('CT','John B. Larson','L000557'),
		('CT','Rosa L. DeLauro','D000216'),
		('CT','Joe Courtney','C001069'),
		('CT','Jahana Hayes','Not Found'),
		('CT','James A. Himes','H001047'),
		('DC','Eleanor Holmes Norton','N000147'),
		('DE','Christopher A. Coons','Not Found'),
		('DE','Thomas R. Carper','C000174'),
		('DE','Lisa Blunt Rochester','B001303'),
		('FL','Marco Rubio','R000595'),
		('FL','Rick Scott','Not Found'),
		('FL','Neal Dunn','Not Found'),
		('FL','Matt Gaetz','G000578'),
		('FL','Aaron Bean','Not Found'),
		('FL','Kat Cammack','Not Found'),
		('FL','Mike Waltz','Not Found'),
		('FL','John Rutherford','Not Found'),
		('FL','Bill Posey','P000599'),
		('FL','Cory Mills','Not Found'),
		('FL','Darren Soto','Not Found'),
		('FL','Sheila Cherfilus McCormick','Not Found'),
		('FL','Daniel Webster','W000806'),
		('FL','Maxwell Frost','Not Found'),
		('FL','Anna Paulina Luna','Not Found'),
		('FL','Gus Bilirakis','Not Found'),
		('FL','Laurel Lee','Not Found'),
		('FL','Kathy Castor','C001066'),
		('FL','Greg Steube','Not Found'),
		('FL','Vern Buchanan','B001260'),
		('FL','Byron Donalds','Not Found'),
		('FL','Scott Franklin','Not Found'),
		('FL','Lois Frankel','Not Found'),
		('FL','Brian Mast','Not Found'),
		('FL','Frederica S. Wilson','W000808'),
		('FL','Jared Moskowitz','Not Found'),
		('FL','Mario Diaz-Balart','Not Found'),
		('FL','Debbie Wasserman Schultz','Not Found'),
		('FL','Carlos A. Gimenez','Not Found'),
		('FL','Maria Elvira Salazar','Not Found'),
		('GA','Jon Ossoff','Not Found'),
		('GA','Raphael G. Warnock','Not Found'),
		('GA','Marjorie Taylor Greene','Not Found'),
		('GA','Rick Allen','Not Found'),
		('GA','David Scott','S001157'),
		('GA','Mike Collins','Not Found'),
		('GA','Barry Loudermilk','Not Found'),
		('GA','Lucy McBath','Not Found'),
		('GA','Austin Scott','Not Found'),
		('GA','Nikema Williams','Not Found'),
		('GA','Rich McCormick','Not Found'),
		('GA','Andrew Clyde','Not Found'),
		('GA','Drew Ferguson','Not Found'),
		('GA','Hank Johnson','Not Found'),
		('GA','Buddy Carter','Not Found'),
		('GA','Sanford D. Bishop, Jr.','B000490'),
		('GU','James Moylan','Not Found'),
		('HI','Brian Schatz','S001194'),
		('HI','Mazie K. Hirono','H001042'),
		('HI','Jill N. Tokuda','Not Found'),
		('HI','Ed Case','Not Found'),
		('IA','Chuck Grassley','G000386'),
		('IA','Joni Ernst','E000295'),
		('IA','Zach Nunn','Not Found'),
		('IA','Randy Feenstra','Not Found'),
		('IA','Mariannette Miller-Meeks','Not Found'),
		('IA','Ashley Hinson','Not Found'),
		('ID','James E. Risch','R000584'),
		('ID','Mike Crapo','C000880'),
		('ID','Michael Simpson','Not Found'),
		('ID','Russ Fulcher','Not Found'),
		('IL','Dick Durbin','D000563'),
		('IL','Tammy Duckworth','D000622'),
		('IL','Eric Sorensen','Not Found'),
		('IL','Lauren Underwood','Not Found'),
		('IL','Nikki Budzinski','Not Found'),
		('IL','Darin LaHood','Not Found'),
		('IL','Mary Miller','S000364'),
		('IL','Brad Schneider','S001190'),
		('IL','Mike Bost','Not Found'),
		('IL','Bill Foster','Not Found'),
		('IL','Jonathan L. Jackson','Not Found'),
		('IL','Mike Quigley','Q000023'),
		('IL','JesÃºs "Chuy" GarcÃ­a','Not Found'),
		('IL','Delia Ramirez','Not Found'),
		('IL','Robin Kelly','Not Found'),
		('IL','Jan Schakowsky','S001145'),
		('IL','Raja Krishnamoorthi','Not Found'),
		('IL','Danny K. Davis','D000096'),
		('IL','Sean Casten','Not Found'),
		('IN','Mike Braun','Not Found'),
		('IN','Todd Young','Y000064'),
		('IN','Erin Houchin','Not Found'),
		('IN','Larry Bucshon','Not Found'),
		('IN','Victoria Spartz','Not Found'),
		('IN','James Baird','Not Found'),
		('IN','AndrÃ© Carson','Not Found'),
		('IN','Greg Pence','Not Found'),
		('IN','Frank J. Mrvan','Not Found'),
		('IN','Jim Banks','Not Found'),
		('IN','Rudy Yakym','Not Found'),
		('KS','Jerry Moran','M000934'),
		('KS','Roger Marshall','Not Found'),
		('KS','Tracey Mann','Not Found'),
		('KS','Jake LaTurner','Not Found'),
		('KS','Sharice Davids','Not Found'),
		('KS','Ron Estes','Not Found'),
		('KY','Mitch McConnell','Not Found'),
		('KY','Rand Paul','P000603'),
		('KY','Andy Barr','B001282'),
		('KY','Harold Rogers','R000395'),
		('KY','Thomas Massie','M001184'),
		('KY','Morgan McGarvey','Not Found'),
		('KY','Brett Guthrie','G000558'),
		('KY','James Comer','Not Found'),
		('LA','Bill Cassidy','C001075'),
		('LA','John Kennedy','Not Found'),
		('LA','Steve Scalise','Not Found'),
		('LA','Clay Higgins','Not Found'),
		('LA','Troy A. Carter, Sr.','Not Found'),
		('LA','Julia Letlow','Not Found'),
		('LA','Mike Johnson','Not Found'),
		('LA','Garret Graves','Not Found'),
		('MA','Edward J. Markey','M000133'),
		('MA','Elizabeth Warren','W000817'),
		('MA','Seth Moulton','M001196'),
		('MA','Katherine Clark','C001101'),
		('MA','Jake Auchincloss','Not Found'),
		('MA','Lori Trahan','Not Found'),
		('MA','James McGovern','M000312'),
		('MA','Richard E. Neal','N000015'),
		('MA','William R. Keating','K000375'),
		('MA','Stephen F. Lynch','L000562'),
		('MA','Ayanna Pressley','Not Found'),
		('MD','Ben Cardin','C000141'),
		('MD','Chris Van Hollen','V000128'),
		('MD','Kweisi Mfume','Not Found'),
		('MD','David Trone','Not Found'),
		('MD','Jamie Raskin','Not Found'),
		('MD','John Sarbanes','S001168'),
		('MD','C. A. Dutch Ruppersberger','R000576'),
		('MD','Steny Hoyer','H000874'),
		('MD','Glenn F. Ivey','Not Found'),
		('MD','Andy Harris','H001052'),
		('ME','Angus S. King, Jr.','Not Found'),
		('ME','Susan M. Collins','C001035'),
		('ME','Chellie Pingree','P000597'),
		('ME','Jared Golden','Not Found'),
		('MI','Debbie Stabenow','S000770'),
		('MI','Gary Peters','P000595'),
		('MI','Lisa McClain','Not Found'),
		('MI','Elissa Slotkin','Not Found'),
		('MI','Daniel T. Kildee','Not Found'),
		('MI','Tim Walberg','Not Found'),
		('MI','Debbie Dingell','Not Found'),
		('MI','Hillary Scholten','Not Found'),
		('MI','Bill Huizenga','Not Found'),
		('MI','Jack Bergman','Not Found'),
		('MI','John Moolenaar','Not Found'),
		('MI','Haley Stevens','Not Found'),
		('MI','John James','Not Found'),
		('MI','Shri Thanedar','Not Found'),
		('MI','Rashida Tlaib','Not Found'),
		('MN','Amy Klobuchar','K000367'),
		('MN','Tina Smith','Not Found'),
		('MN','Angie Craig','Not Found'),
		('MN','Dean Phillips','Not Found'),
		('MN','Brad Finstad','Not Found'),
		('MN','Pete Stauber','Not Found'),
		('MN','Tom Emmer','Not Found'),
		('MN','Michelle Fischbach','Not Found'),
		('MN','Betty McCollum','Not Found'),
		('MN','Ilhan Omar','Not Found'),
		('MO','Eric Schmitt','Not Found'),
		('MO','Josh Hawley','Not Found'),
		('MO','Jason Smith','S001195'),
		('MO','Eric Burlison','Not Found'),
		('MO','Sam Graves','Not Found'),
		('MO','Emanuel Cleaver','C001061'),
		('MO','Mark Alford','Not Found'),
		('MO','Blaine Luetkemeyer','L000569'),
		('MO','Ann Wagner','W000812'),
		('MO','Cori Bush','Not Found'),
		('MP','Gregorio Sablan','S001177'),
		('MS','Cindy Hyde-Smith','Not Found'),
		('MS','Roger Wicker','W000437'),
		('MS','Michael Guest','Not Found'),
		('MS','Mike Ezell','Not Found'),
		('MS','Trent Kelly','Not Found'),
		('MS','Bennie Thompson','Not Found'),
		('MT','Jon Tester','T000464'),
		('MT','Steve Daines','D000618'),
		('MT','Matt Rosendale','Not Found'),
		('MT','Ryan K. Zinke','Not Found'),
		('NC','Ted Budd','Not Found'),
		('NC','Thom Tillis','T000476'),
		('NC','Patrick McHenry','M001156'),
		('NC','Jeff Jackson','Not Found'),
		('NC','Wiley Nickel','Not Found'),
		('NC','Alma Adams','Not Found'),
		('NC','Chuck Edwards','Not Found'),
		('NC','David Rouzer','Not Found'),
		('NC','Kathy Manning','Not Found'),
		('NC','Virginia Foxx','Not Found'),
		('NC','Valerie Foushee','Not Found'),
		('NC','Gregory F. Murphy','Not Found'),
		('NC','Deborah Ross','Not Found'),
		('NC','Don Davis','Not Found'),
		('NC','Richard Hudson','Not Found'),
		('NC','Dan Bishop','Not Found'),
		('ND','John Hoeven','H001061'),
		('ND','Kevin Cramer','C001096'),
		('ND','Kelly Armstrong','Not Found'),
		('NE','Deb Fischer','F000463'),
		('NE','Pete Ricketts','Not Found'),
		('NE','Mike Flood','Not Found'),
		('NE','Adrian Smith','S001172'),
		('NE','Don Bacon','Not Found'),
		('NH','Jeanne Shaheen','S001181'),
		('NH','Margaret Wood Hassan','Not Found'),
		('NH','Ann Kuster','K000382'),
		('NH','Chris Pappas','Not Found'),
		('NJ','Cory A. Booker','B001288'),
		('NJ','Robert Menendez','M000639'),
		('NJ','Bonnie Watson Coleman','W000822'),
		('NJ','Donald M. Payne, Jr.','P000604'),
		('NJ','Mikie Sherrill','Not Found'),
		('NJ','Jefferson Van Drew','Not Found'),
		('NJ','Donald Norcross','N000188'),
		('NJ','Christopher H. Smith','S000522'),
		('NJ','Andy Kim','Not Found'),
		('NJ','Frank Pallone, Jr.','P000034'),
		('NJ','Josh Gottheimer','Not Found'),
		('NJ','Robert J. Menendez','Not Found'),
		('NJ','Thomas H. Kean, Jr.','Not Found'),
		('NJ','Bill Pascrell, Jr.','P000096'),
		('NM','Ben Ray LujÃ¡n','Not Found'),
		('NM','Martin Heinrich','H001046'),
		('NM','Melanie Stansbury','Not Found'),
		('NM','Teresa Leger Fernandez','Not Found'),
		('NM','Gabe Vasquez','Not Found'),
		('NV','Catherine Cortez Masto','C001113'),
		('NV','Jacky Rosen','Not Found'),
		('NV','Steven A. Horsford','Not Found'),
		('NV','Susie Lee','Not Found'),
		('NV','Mark Amodei','A000369'),
		('NV','Dina Titus','T000468'),
		('NY','Charles E. Schumer','S000148'),
		('NY','Kirsten E. Gillibrand','G000555'),
		('NY','Nydia M. VelÃ¡zquez','V000081'),
		('NY','Grace Meng','M001188'),
		('NY','Yvette D. Clarke','C001067'),
		('NY','Hakeem Jeffries','J000294'),
		('NY','Nicholas J. LaLota','Not Found'),
		('NY','George A. D. Santos','Not Found'),
		('NY','Andrew R. Garbarino','Not Found'),
		('NY','Gregory W. Meeks','M001137'),
		('NY','Anthony P. D''Esposito','Not Found'),
		('NY','Michael V. Lawler','Not Found'),
		('NY','Pat Ryan','Not Found'),
		('NY','Marcus Molinaro','Not Found'),
		('NY','Adriano Espaillat','E000297'),
		('NY','Alexandria Ocasio-Cortez','Not Found'),
		('NY','Ritchie Torres','Not Found'),
		('NY','Jamaal Bowman','Not Found'),
		('NY','Daniel Goldman','Not Found'),
		('NY','Nicole Malliotakis','Not Found'),
		('NY','Jerrold L. Nadler','Not Found'),
		('NY','Claudia Tenney','Not Found'),
		('NY','Joseph Morelle','Not Found'),
		('NY','Brian Higgins','H001038'),
		('NY','Paul D. Tonko','T000469'),
		('NY','Elise Stefanik','Not Found'),
		('NY','Brandon M. Williams','Not Found'),
		('NY','Nick Langworthy','Not Found'),
		('OH','JD Vance','Not Found'),
		('OH','Sherrod Brown','B000944'),
		('OH','Greg Landsman','Not Found'),
		('OH','Joyce Beatty','B001281'),
		('OH','Brad Wenstrup','W000815'),
		('OH','Marcy Kaptur','K000009'),
		('OH','Warren Davidson','Not Found'),
		('OH','Bob Latta','L000566'),
		('OH','Jim Jordan','J000289'),
		('OH','Max Miller','Not Found'),
		('OH','Bill Johnson','J000292'),
		('OH','Michael Turner','T000463'),
		('OH','David Joyce','J000295'),
		('OH','Emilia Sykes','Not Found'),
		('OH','Troy Balderson','Not Found'),
		('OH','Shontel Brown','Not Found'),
		('OH','Mike Carey','Not Found'),
		('OK','James Lankford','L000575'),
		('OK','Markwayne Mullin','I000024'),
		('OK','Frank Lucas','L000491'),
		('OK','Tom Cole','C001053'),
		('OK','Stephanie Bice','Not Found'),
		('OK','Kevin Hern','Not Found'),
		('OK','Josh Brecheen','Not Found'),
		('OR','Jeff Merkley','M001176'),
		('OR','Ron Wyden','W000779'),
		('OR','Val Hoyle','Not Found'),
		('OR','Lori Chavez-DeRemer','Not Found'),
		('OR','Cliff Bentz','Not Found'),
		('OR','Earl Blumenauer','B000574'),
		('OR','Suzanne Bonamici','Not Found'),
		('OR','Andrea Salinas','Not Found'),
		('PA','Bob Casey','C001070'),
		('PA','John Fetterman','Not Found'),
		('PA','Chrissy Houlahan','Not Found'),
		('PA','Susan Wild','Not Found'),
		('PA','Madeleine Dean','Not Found'),
		('PA','Mary Gay Scanlon','Not Found'),
		('PA','Matt Cartwright','Not Found'),
		('PA','Daniel Meuser','Not Found'),
		('PA','Brendan Boyle','Not Found'),
		('PA','Dwight Evans','Not Found'),
		('PA','Brian Fitzpatrick','Not Found'),
		('PA','Mike Kelly','Not Found'),
		('PA','Glenn "GT" Thompson','Not Found'),
		('PA','Chris Deluzio','Not Found'),
		('PA','Scott Perry','Not Found'),
		('PA','Summer Lee','Not Found'),
		('PA','Lloyd Smucker','Not Found'),
		('PA','Guy Reschenthaler','Not Found'),
		('PA','John Joyce','Not Found'),
		('PR','Jenniffer GonzÃ¡lez-ColÃ³n','Not Found'),
		('RI','Jack Reed','R000122'),
		('RI','Sheldon Whitehouse','W000802'),
		('RI','Seth M. Magaziner','Not Found'),
		('RI','David Cicilline','Not Found'),
		('SC','Lindsey Graham','G000359'),
		('SC','Tim Scott','S001184'),
		('SC','Nancy Mace','Not Found'),
		('SC','Joe Wilson','W000795'),
		('SC','Russell Fry','Not Found'),
		('SC','Ralph Norman','Not Found'),
		('SC','James E. Clyburn','Not Found'),
		('SC','Jeff Duncan','D000615'),
		('SC','William Timmons','Not Found'),
		('SD','John Thune','T000250'),
		('SD','Mike Rounds','R000605'),
		('SD','Dusty Johnson','Not Found'),
		('TN','Bill Hagerty','Not Found'),
		('TN','Marsha Blackburn','Not Found'),
		('TN','Mark Green','Not Found'),
		('TN','David Kustoff','Not Found'),
		('TN','Andy Ogles','Not Found'),
		('TN','John W. Rose','Not Found'),
		('TN','Steve Cohen','C001068'),
		('TN','Chuck Fleischmann','F000459'),
		('TN','Scott DesJarlais','D000616'),
		('TN','Diana Harshbarger','Not Found'),
		('TN','Tim Burchett','Not Found'),
		('TX','John Cornyn','C001056'),
		('TX','Ted Cruz','Not Found'),
		('TX','Wesley Hunt','Not Found'),
		('TX','Greg Casar','Not Found'),
		('TX','Vicente Gonzalez','Not Found'),
		('TX','Lloyd Doggett','Not Found'),
		('TX','Brian Babin','Not Found'),
		('TX','Henry Cuellar','C001063'),
		('TX','Michael Cloud','Not Found'),
		('TX','Sylvia Garcia','Not Found'),
		('TX','Beth Van Duyne','Not Found'),
		('TX','Tony Gonzales','Not Found'),
		('TX','Michael C. Burgess','B001248'),
		('TX','Roger Williams','W000816'),
		('TX','John Carter','C001051'),
		('TX','Jasmine Crockett','Not Found'),
		('TX','Marc Veasey','V000131'),
		('TX','Colin Allred','Not Found'),
		('TX','Pete Sessions','Not Found'),
		('TX','Veronica Escobar','Not Found'),
		('TX','Jodey Arrington','Not Found'),
		('TX','Sheila Jackson Lee','J000032'),
		('TX','Ronny Jackson','Not Found'),
		('TX','Kay Granger','G000377'),
		('TX','Monica De La Cruz','Not Found'),
		('TX','Randy Weber','W000814'),
		('TX','Joaquin Castro','C001091'),
		('TX','Troy Nehls','Not Found'),
		('TX','Chip Roy','Not Found'),
		('TX','August Pfluger','Not Found'),
		('TX','Michael McCaul','M001157'),
		('TX','Nathaniel Moran','Not Found'),
		('TX','Dan Crenshaw','Not Found'),
		('TX','Lance Gooden','Not Found'),
		('TX','Jake Ellzey','Not Found'),
		('TX','Keith Self','Not Found'),
		('TX','Pat Fallon','Not Found'),
		('TX','Al Green','G000553'),
		('TX','Lizzie Fletcher','Not Found'),
		('TX','Morgan Luttrell','Not Found'),
		('UT','Mike Lee','L000577'),
		('UT','Mitt Romney','Not Found'),
		('UT','Blake D. Moore','Not Found'),
		('UT','John R. Curtis','Not Found'),
		('UT','Chris Stewart','S001192'),
		('UT','Burgess Owens','Not Found'),
		('VA','Mark R. Warner','W000805'),
		('VA','Tim Kaine','K000384'),
		('VA','Bob Good','Not Found'),
		('VA','Jennifer McClellan','Not Found'),
		('VA','Bobby Scott','S000185'),
		('VA','Jen Kiggans','Not Found'),
		('VA','Rob Wittman','W000804'),
		('VA','Morgan Griffith','G000568'),
		('VA','Don Beyer','B001292'),
		('VA','Abigail Spanberger','Not Found'),
		('VA','Ben Cline','Not Found'),
		('VA','Jennifer Wexton','Not Found'),
		('VA','Gerry Connolly','C001078'),
		('VI','Stacey E. Plaskett','P000610'),
		('VT','Bernie Sanders','S000033'),
		('VT','Peter Welch','W000800'),
		('VT','Becca Balint','Not Found'),
		('WA','Maria Cantwell','C000127'),
		('WA','Patty Murray','M001111'),
		('WA','Marilyn Strickland','Not Found'),
		('WA','Adam Smith','S000510'),
		('WA','Derek Kilmer','K000381'),
		('WA','Cathy McMorris Rodgers','M001159'),
		('WA','Kim Schrier','Not Found'),
		('WA','Pramila Jayapal','Not Found'),
		('WA','Rick Larsen','L000560'),
		('WA','Suzan DelBene','D000617'),
		('WA','Dan Newhouse','N000189'),
		('WA','Marie Gluesenkamp Perez','Not Found'),
		('WI','Ron Johnson','J000293'),
		('WI','Tammy Baldwin','B001230'),
		('WI','Scott Fitzgerald','Not Found'),
		('WI','Glenn Grothman','G000576'),
		('WI','Tom Tiffany','Not Found'),
		('WI','Mike Gallagher','Not Found'),
		('WI','Bryan Steil','Not Found'),
		('WI','Mark Pocan','P000607'),
		('WI','Derrick Van Orden','Not Found'),
		('WI','Gwen Moore','M001160'),
		('WV','Joe Manchin','M001183'),
		('WV','Shelley Moore Capito','C001047'),
		('WV','Alex Mooney','M001195'),
		('WV','Carol Miller','Not Found'),
		('WY','Cynthia M. Lummis','Not Found'),
		('WY','John Barrasso','B001261'),
		('WY','Harriet Hageman','Not Found')
		) raw (state,name,bioguide_id)
	WHERE POSITION(us_congress.last_name in raw.name) > 0
		AND raw.state = us_congress.state
	)
FROM us_congress
WHERE google_api_name IS NULL
--ORDER BY google_api_name
ORDER BY last_name,full_name
;